version: '3.1'

services:

  db:
    image: mongo:6.0.4
    container_name: mongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - default
    volumes:
      - mongo-db-dev:/data/db

  app-server:
    image:  ${DOCKER_HUB_USERNAME}/suigetsu-project:latest
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${HOST}
      PORT: ${PORT}
      ENV: dev
    ports:
      - '${PORT}:${PORT}'
    restart: always
    networks:
      - default
    depends_on:
      - db
volumes:
  mongo-db-dev: