version: '3.1'

services:

  db-prod:
    image: mongo:6.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - default
    volumes:
      - mongo-db-prod:/data/db

  app-server-prod:
    image:  ${DOCKER_HUB_USERNAME}/suigetsu-project:latest
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      PORT: ${PORT}
      MONGO_HOST: ${HOST}
      ENV: prod
    ports:
      - '${PORT}:${PORT}'
    restart: always
    networks:
      - default
    depends_on:
      - db-prod

volumes:
  mongo-db-prod: