version: '3.8' # อัปเดตเวอร์ชันเป็น 3.8 เพื่อรองรับ `condition`

services:

  db:
    image: mongo:6.0.4
    container_name: mongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - default
    volumes:
      - mongo-db-dev:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 3

  app-server:
    image: ${DOCKER_HUB_USERNAME}/suigetsu-project:latest
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${HOST}
      PORT: ${PORT}
      ENV: dev
    ports:
      - '${PORT}:${PORT}'
    restart: always
    networks:
      - default
    depends_on:
      db:
        condition: service_healthy

volumes:
  mongo-db-dev:
    driver: local
