name: deploy prod
on:
  push:
    branches:
      - production

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: prod
    env:
      HOST: ${{ secrets.HOST }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
      MONGO_PORT: ${{ secrets.MONGO_PROD_PORT }}
      PORT: 8081
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/suigetsu-project:latest
      -
        name: Prepare the docker-compose run
        run: |
              ls -l
      - 
        name: Prepare docker-compose run
        run: |
              mkdir suigetsu-project-prod
              cp docker-compose.prod.yml suigetsu-project-prod/docker-compose.prod.yml
              cd suigetsu-project-prod
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.prod.yml down
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.prod.yml pull
              docker-compose -H ${{ secrets.DOCKER_HOST_SERVER }} -f docker-compose.prod.yml up -d